name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]
jobs:
  Test-script:
    runs-on: ubuntu-latest
    env:
      input: "\n1\nnickname\nredacted\n20 GB"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: chmod +x tor.sh
      - run: echo "$input" | sudo ./tor.sh
      - run: |
          start_time=$(date +%s)
          while true; do
              if journalctl -xeu tor@default | grep -q "Bootstrapped 100%"; then
                  echo "Success!"
                  exit 0
              fi

              current_time=$(date +%s)
              elapsed_time=$((current_time - start_time))

              if [ $elapsed_time -ge 30 ]; then
                  echo "Turtle + Daniela <3"
                  exit 1
              fi
              sleep 1
          done
